### ISSUE TITLE
Can you add "Auto Smooth option to the books?

### ISSUE THREAD

**Issue by Oxervision** [ldo/blender_bookmaker#1]
Hi, the first, thanks for the addon. As title says it would be good to have an option to auto smooth the books created, if you create the book in SIngle Object is very easy auto smooth one object but If you prefer create as separate objects it's very tedious smooth one to one.

**Comment by ldo** [comment]
Done. https://github.com/ldo/blender_bookmaker/commit/c85491b802388ac29d59f2c415a66cf8fee71e6d
